#!/bin/bash

# Exit on error
set -o errexit

# Get diff tool
tool="$(git config --get --global diff.tool)"

# Get diff tool cmd
cmd="$(git config --get --global difftool.$tool.cmd)"

# Run and exit if found
if [[ "$cmd" != "" ]]; then
    REMOTE="$1"
    LOCAL="$2"
    $cmd
    exit
fi

# Get diff tool path
cmd="$(git config --get --global difftool.$tool.path)"

# Run and exit if found
if [[ "$cmd" != "" ]]; then
    $cmd $@
    exit
fi

# Get command from tool keyword
if [[ "$tool" == "bc" || "$tool" == "bc3" ]]; then
    cmd="bcompare"
elif [[ "$tool" == "vimdiff" || "$tool" == "vimdiff2" || "$tool" == "vimdiff3" ]]; then
    cmd="vimdiff"
elif [[ "$tool" == "araxis" ]]; then
    cmd="compare"
elif [[ "$tool" == "codecompare" ]]; then
    cmd="CodeCompare"
elif [[ "$tool" == "deltawalker" ]]; then
    cmd="DeltaWalker"
elif [[ "$tool" == "emerge" ]]; then
    cmd="emacs"
elif [[ "$tool" == "gvimdiff" || "$tool" == "gvimdiff2" || "$tool" == "gvimdiff3" ]]; then
    cmd="gvim"
elif [[ "$tool" == "winmerge" ]]; then
    cmd="WinMergeU"
else
    # Other commands match the keyword (e.g. "kdiff3")
    cmd="$tool"
fi

# Run
$cmd $@
